version: '3'

services:
  squid-deb-proxy:
    build: .
    container_name: squid-deb-proxy
    hostname: squid-deb-proxy
    ports:
      - "3143:8000/tcp"
    volumes:
      - ./squid:/data/squid
    environment:
      TZ: "America/Chicago"
    restart: unless-stopped