# validate YAML
# https://codebeautify.org/yaml-validator

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # every Sunday at midnight

name: Build and Save Docker Image

jobs:
  build:
    name: Build and Check Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Build docker
        id: docker_build
        # https://github.com/docker/build-push-action
        uses: docker/build-push-action@v5
        with:
          push: false
          context: "{{defaultContext}}:squid-deb-proxy"
          tags: ghcr.io/firefly2442/docker-squid-deb-proxy:latest
          platforms: linux/amd64
          # Load is a shorthand for --output=type=docker (default false)
          load: true
          # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
          # cache-from: type=registry,ref=ghcr.io/firefly2442/docker-squid-deb-proxy:latest
          # cache-to: type=inline
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          ignore-unfixed: true
          image-ref: 'ghcr.io/firefly2442/docker-squid-deb-proxy:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'